# -- common settings --
date.pattern=dd-MM-yyyy
sqlDate.pattern=yyyy-MM-dd

summa.text=ppo no
webapp.name=Tamil Nadu e-District
webapp.tagline=A Citizen-centric portal
company.name=Designed & Hosted By: <a href="http://www.tn.nic.in" target="_blank">National Informatics Centre, Chennai.</a>
company.url=http://www.tn.nic.in

menu.status = Status
menu.scholarships = Scholarships
menu.grievances = Grievances
menu.utility = Utility
menu.department = Departments
menu.contactus = Contact Us

menu.masters = Master

menu.editInstDetails = Edit Institution Details
menu.changepassword = Change Password
menu.scholar_disbursement = Scholarships Disbursement

menu.user_management = User Management
menu.scholar_fee_mgmt = Scholarship Fee Management
menu.fund_mgmt = Fund Management
menu.mis_report = MIS Reports

menu.editInstitutionalDetail = Update Institution Details
menu.changePassword = Change Password
menu.scholarship = Scholarship
menu.scholarshipDisbursement = Scholarship Disbursement
menu.refundList = Refund

menu.applicationScrutiny = Application Scrutiny
menu.proceedings = Proceedings
menu.chequeDisbursement = Cheque Disbursement
menu.acknowledgement = Acknowledgement

menu.applicationOverview = Scrutiny Overview
menu.district.status = Status
menu.sanctionproceeding = Sanction Proceedings
menu.chequeDisbursementOverview = Cheque Disbursement Overview
menu.acknowledgementOverview = Ack Overview
menu.proceedingOrder = Proceeding Order

menu.logout = Logout

errors.required=${getText(fieldName)} is a required field.

universityMaster.title = University Master
universityMaster.heading = University Master Entry
university.code = University Code
university.universityName = Name of the University
university = University

course.title = Course Master
course.heading = Course Master Entry
course.courseCode = Course Code
stream.stream = Stream
course.courseName = Name of the Course

courseSubject.title = Subject Master
courseSubject.heading = Subject Master Entry
courseSubject.courseCode = Course
courseSubject.streamCode = Course Stream
courseSubject.courseType = Course Type
courseSubject.courseSubCode = Subject Code
courseSubject.subjectName = Name of the Subject
courseSubject.duration = Duration of the Course
courseSubject.grad = Scholarship Type

caste.title = Caste Master
caste.heading = Caste Master Entry
caste.casteCode = Caste Code
caste.commName = Community
caste.casteName = Name of the Caste


boardingMaster.title = Boarding & Lodging Master
boardingMaster.heading = Boarding & Lodging Master Entry
boarding.amount = Amount
boarding.select = Select Place
boarding.stream = Stream Type 
boarding.code = District Code
boarding.place = Place
university.name = University Name

hostelMaster.title = Hostel Master
hostelMaster.heading = Hostel Master Entry
hostel.code = Hostel Code
hostel.name = Hostel Name
hostel.inst = Institution Name
hostel.add  = Hostel Address
hostel.pin = PinCode
hostel=Hostel
hostelAddress.talukCode = Taluk
hostelAddress.districtCode = District


instituteMaster.title = Institution Master
instituteMaster.heading = Institution Master Entry
institute.code = Institute Code
institute.name = Institute Name
institution.courseOffered = Courses Offered
institution = Institution


instMaster.title = Institution Master
instMaster.heading = Institution Master Entry
inst=Institution
name = Name
deisgnation = Designation
dobirth = Date of Birth
sex = Sex
mobile = Mobile
inst.name = Name of the Institution
inst.reg = Registration Number
inst.aff = Affiliated to
inst.mail = E-Mail(Institution)
inst.fax = Fax(Institution)
inst.tele = Telephone(Institution)
inst.cadd = Current Address
inst.radd = Registered Address
inst.door = Door No.
inst.street = Street Name
inst.local = Locality
inst.city = City
inst.pin = Pincode
inst.pbank = Primary Bank
inst.sbank = Secondary Bank
inst.payee = Name of the Payee
inst.bank = Name of the Bank
inst.branch =Branch Address
inst.branchcode = Branch Name
inst.accno = Account Number
inst.typeofba = Type of Bank Account
inst.mcr = MCR Code
inst.transfer = Type of Transfer Available 

religionMaster.title = Religion Master
religionMaster.heading = Religion Master Entry
religion.religionCode = Religion Code
religion.religionName = Religion Name
religion = Religion

communityMaster.title = Community Master
communityMaster.heading = Community Master Entry
community.commCode = Community Code
community.commName = Community Name
community = Community

bankMaster.title = Bank Master
bankMaster.heading = Bank Master Entry
bank.bankCode = Bank Code
bank.bankName = Bank Name
bank.bankShortName = Bank Short Name
bank = Bank

accountHeadMaster.title = Account Head Master
accountHeadMaster.heading = Account Head Master Entry
accountHead.accHeadCode = Account Head Code
accountHead.accHeadName = Account Head Name
accountHead.commCode = Community
accountHead.scholarshipCode = Scholarship
accountHead = Account Head

postmetFee.title = Post Metric Fee Structure Master
postmetFee.heading = Post Metric Fee Structure Master Entry
postmetFee.courseSubCode = Course
postmetFee.bookMoney = Book Money
postmetFee.splFee = Special Fee
postmetFee.tutFee = Tuition Fee
postmetFee.courseYear = Course Year

examFeeMaster.title = Exam Fee Structure
examFeeMaster.heading = Exam Fee Structure Entry
examFee.districtCode = District
examFee.instCode = Intitution
examFee.courseSubCode = Course & Subject
examFee.courseYear = Course Year
examFee.academicYr = Academic Year
examFee.examFee = Exam Fee
examFee = Exam Fee Structure


bankBranchMaster.title = Bank Branch Master
bankBranchMaster.heading = Bank Branch Master Entry
bankBranch.bankCode = Bank
bankBranch.bankBrCode = Branch Code
bankBranch.branchName = Branch Name
bankBranch.address = Address
bankBranch.pincode = Pincode
bankBranch.brMicrcode = Micr Code
bankBranch.districtCode = District 
bankBranch.talukCode = Taluk 
bankBranch = Bank Branch

freePostmatricFeeMaster.title = Free and Postmatric Fee Structure
freePostmatricFeeMaster.heading = Free and Postmatric Fee Structure Report

instituteAmountreportMaster.title = Institute Amount Report
instituteAmountreportMaster.heading =Institute Amount Report 

districtwisescholar.title = Districtwise Scholarship Amount Disbursed
districtwisescholar.heading = Districtwise Scholarship Amount Disbursed

districtwiseAmountdisburse = Districtwise Amount Disburse Report 



freeEduCeilingFeeMaster.title = Free Education Ceiling Fee Structure
freeEduCeilingFeeMaster.heading = Free Education Ceiling Fee Structure Entry
freeEduCeilingFee.districtCode = District
freeEduCeilingFee.instCode = Intitution
freeEduCeilingFee.courseSubCode = Course & Subject
freeEduCeilingFee.courseYear = Course Year
freeEduCeilingFee.academicYr = Academic Year
freeEduCeilingFee.splFee = Special Fee
freeEduCeilingFee.tutFee = Tuition Fee 
freeEduCeilingFee.examFee = Exam Fee
freeEduCeilingFee.compFee = Compulsory Fee
freeEduCeilingFee = Free Education Ceiling Fee Structure

institute.summaryDetails = Institution Summary
name.institute = Name of the Institution
user.id = User Id

student.entry.heading = Application form for Scholarship Scheme
student.entry.title = Application form for Scholarship Scheme
student.name = Student Name


user.status=Logged in as\: 
user.logout=Logout

home=Home
back=Back

district=District
pleaseSelect=Please Select ...


# -- index page values --
index.Title=Welcome! Index
index.content=content

login.heading=Login
login.title=Login
input.username=Username
input.password=Password
login.button=Login


errors.existing.university = {0} is already Existing

